# Generated by Django 4.2.1 on 2023-07-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='prequisite',
            new_name='prerequisite',
        ),
    ]
