# Generated by Django 4.2.1 on 2023-07-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olapp', '0002_rename_prequisite_quiz_prerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='membership',
            field=models.CharField(choices=[('G', 'Gold'), ('S', 'Silver')], default='S', max_length=1),
        ),
    ]
