# Generated by Django 4.2.1 on 2023-07-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olapp', '0003_student_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olapp.student')),
            ],
        ),
    ]
