# Generated by Django 4.2.1 on 2023-07-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olapp', '0005_quizscore_graded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseEnrolment',
        ),
    ]
